language: node_js

before_deploy:
  # build the docs for the API
  - npm run docs
  # file to tell GitHub pages not to try to run jekyll stuff (can break urls)
  - touch docs/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  verbose: true
  local-dir: docs/
  github-token: $GH_TOKEN
  on:
    branch: master
